config/routes.rb
Rails.application.routes.draw do
  resources :teams_creators
  resources :teams
  resources :matches_creators
  resources :matches
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # get "/create-registrations" => "registrations#create_registrations"
  get "/results" => "results#index"

  # match '/destroy_them_all', to: 'registrations_creators#destroy_them_all', via: :delete
  match '/destroy_all', to: 'home#destroy_all', via: :delete
  match '/destroy_all', to: 'home#destroy_all', via: :get

  # Defines the root path route ("/")
  root "home#index"
end

app/models/matches_creator.rb
class MatchCreatorValidator < ActiveModel::Validator

  # checks if a string is a number
  def is_numeric(o)
    true if Integer(o) rescue false
  end
  
  def validate(record)
    matches_to_create = record.user_input.split("\n")

    matches_to_create.each do |m|
      fields = m.split(" ")
      if fields.size < 4
        record.errors.add :user_input, "Missing Arguments"
      elsif fields.size > 4
        record.errors.add :user_input, "Too Many Arguments"
      
      else
        team1_name = fields[0]
        team2_name = fields[1]
        team1_score = fields[2]
        team2_score = fields[3]
  
        if !is_numeric(team1_score) or !is_numeric(team2_score)
          record.errors.add :user_input, "Team1 and Team2 scores must be integers"
        end


        if Team.find_by(name: team1_name) == nil
          record.errors.add :user_input, "First team is not registered"
        end

        if Team.find_by(name: team2_name) == nil
          record.errors.add :user_input, "Second team is not registered"
        end

        if Team.find_by(name: team1_name).group != Team.find_by(name: team2_name).group
          record.errors.add :user_input, "Cannot have match between teams from different groups"
        end

        if team1_name == team2_name
          record.errors.add :user_input, "Cannot have match between the same team"
        end

      end
      
    end

  end
end

class MatchesCreator < ApplicationRecord
  validates :user_input, presence: true 
  validates_with MatchCreatorValidator
end

app/controllers/matches_creators_controller.rb
class MatchesCreatorsController < ApplicationController
  before_action :set_matches_creator, only: %i[ show edit update destroy ]

  # GET /matches_creators/new
  def new
    @matches_creator = MatchesCreator.new
  end

  # GET /matches_creators/1/edit
  def edit
  end

  # POST /matches_creators or /matches_creators.json
  def create
    @matches_creator = MatchesCreator.new(matches_creator_params)
    respond_to do |format|
      if @matches_creator.save
        # Create the respective registrations based on user input
        @user_inputs = @matches_creator.user_input.split("\n")
        @user_inputs.each do |input|
          fields = input.split(" ")
          first_team = fields[0]
          first_team_id = Team.find_by(name: first_team) == nil ? -1 : Team.find_by(name: first_team).id.to_i
          second_team = fields[1]
          # second_team_id = Team.find_by(name: second_team).id.to_i
          second_team_id = Team.find_by(name: second_team) == nil ? -1 : Team.find_by(name: second_team).id.to_i

          first_team_score = fields[2]
          second_team_score = fields[3]

          Match.create(team1_id: first_team_id, team2_id: second_team_id, team1_score: first_team_score, team2_score: second_team_score)
        end
        format.html { redirect_to matches_path, notice: "Matches were successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @matches_creator.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_matches_creator
      @matches_creator = MatchesCreator.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def matches_creator_params
      params.require(:matches_creator).permit(:user_input)
    end
end

app/helpers/matches_creators_helper.rb
module MatchesCreatorsHelper
end

app/views/matches_creators/_form.html.erb
<%= form_with(model: matches_creator) do |form| %>
  <% if matches_creator.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(matches_creator.errors.count, "error") %> prohibited this matches_creator from being saved:</h2>

      <ul>
        <%@matches_creator.errors.messages.values.each do |msg| %>
          <%msg.each do  |m| %>
            <li><%= m %></li>
          <%end %>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_input, style: "display: block" %>
    <%= form.text_area :user_input %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/matches_creators/_matches_creator.html.erb
<div id="<%= dom_id matches_creator %>">
  <p>
    <strong>User input:</strong>
    <%= matches_creator.user_input %>
  </p>

</div>

app/views/matches_creators/edit.html.erb
<h1>Editing matches creator</h1>

<%= render "form", matches_creator: @matches_creator %>

<br>

<div>
  <%= link_to "Show this matches creator", @matches_creator %> |
  <%= link_to "Back to matches creators", matches_creators_path %>
</div>

app/views/matches_creators/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Matches creators</h1>

<div id="matches_creators">
  <% @matches_creators.each do |matches_creator| %>
    <%= render matches_creator %>
    <p>
      <%= link_to "Show this matches creator", matches_creator %>
    </p>
  <% end %>
</div>

<%= link_to "New matches creator", new_matches_creator_path %>
<%= link_to "Home", root_path %>

app/views/matches_creators/new.html.erb
<h1>New matches creator</h1>

<%= render "form", matches_creator: @matches_creator %>

<br>

<div>
  <%= link_to "Home", root_path %>
</div>

app/views/matches_creators/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @matches_creator %>

<div>
  <%= link_to "Edit this matches creator", edit_matches_creator_path(@matches_creator) %> |
  <%= link_to "Back to matches creators", matches_creators_path %>

  <%= button_to "Destroy this matches creator", @matches_creator, method: :delete %>
</div>