config/routes.rb
Rails.application.routes.draw do
  resources :teams_creators
  resources :teams
  resources :matches_creators
  resources :matches
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # get "/create-registrations" => "registrations#create_registrations"
  get "/results" => "results#index"

  # match '/destroy_them_all', to: 'registrations_creators#destroy_them_all', via: :delete
  match '/destroy_all', to: 'home#destroy_all', via: :delete
  match '/destroy_all', to: 'home#destroy_all', via: :get

  # Defines the root path route ("/")
  root "home#index"
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :team1, :class_name => "Team"
  belongs_to :team2, :class_name => "Team"

  def is_draw
    return team1_score == team2_score
  end

  def get_winner
    if is_draw
      p "Draw"
      return -1
    end

    if team1_score > team2_score
      return team1_id
    else
      return team2_id
    end
  end

  def get_loser
    if is_draw
      p "Draw"
      return -1
    end

    if team1_score < team2_score
      return team1_id
    else
      return team2_id
    end
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: %i[ show edit update destroy ]

  # GET /matches or /matches.json
  def index
    @matches = Match.all.includes(:team1, :team2)
  end

  # GET /matches/1 or /matches/1.json
  def show
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # POST /matches or /matches.json
  def create
    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to match_url(@match), notice: "Match was successfully created." }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def match_params
      params.require(:match).permit(:team1_id, :team2_id, :team1_score, :team2_score)
    end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.erb
<%= form_with(model: match) do |form| %>
  <% if match.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
        <% match.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :registration_id, style: "display: block" %>
    <%= form.number_field :registration_id %>
  </div>

  <div>
    <%= form.label :opponent_id, style: "display: block" %>
    <%= form.number_field :opponent_id %>
  </div>

  <div>
    <%= form.label :registration_score, style: "display: block" %>
    <%= form.number_field :registration_score %>
  </div>

  <div>
    <%= form.label :opponent_score, style: "display: block" %>
    <%= form.number_field :opponent_score %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/matches/_match.html.erb
<div id="<%= dom_id match %>">
  <p>
    <strong>Team1:</strong>
    <%= match.team1.name %>
  </p>

  <p>
    <strong>Team2:</strong>
    <%= match.team2.name %>
  </p>

  <p>
    <strong>Team1 score:</strong>
    <%= match.team1_score %>
  </p>

  <p>
    <strong>Team2 score:</strong>
    <%= match.team2_score %>
  </p>

</div>

app/views/matches/edit.html.erb
<h1>Editing match</h1>

<%= render "form", match: @match %>

<br>

<div>
  <%= link_to "Show this match", @match %> |
  <%= link_to "Back to matches", matches_path %>
</div>

app/views/matches/index.html.erb
<h1>Matches</h1>

<div>
  <%= link_to "Home", root_path %>
</div>

<div id="matches">
  <table>
    <thead>
      <tr>
        <th>Team 1</th>
        <th>Team 2</th>
        <th>Score</th>
      </tr>
    </thead>

    <tbody>
      <% @matches.each do |m| %>
        <tr>
          <td><%= m.team1.name %></td>
          <td><%= m.team2.name %></td>
          <td><%= m.team1_score %> - <%= m.team2_score %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/matches/new.html.erb
<h1>New match</h1>

<%= render "form", match: @match %>

<br>

<div>
  <%= link_to "Back to matches", matches_path %>
</div>

app/views/matches/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @match %>

<div>
  <%= link_to "Edit this match", edit_match_path(@match) %> |
  <%= link_to "Back to matches", matches_path %>

  <%= button_to "Destroy this match", @match, method: :delete %>
</div>