config/routes.rb
Rails.application.routes.draw do
  resources :teams_creators
  resources :teams
  resources :matches_creators
  resources :matches
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # get "/create-registrations" => "registrations#create_registrations"
  get "/results" => "results#index"

  # match '/destroy_them_all', to: 'registrations_creators#destroy_them_all', via: :delete
  match '/destroy_all', to: 'home#destroy_all', via: :delete
  match '/destroy_all', to: 'home#destroy_all', via: :get

  # Defines the root path route ("/")
  root "home#index"
end

app/models/teams_creator.rb
class TeamCreatorValidator < ActiveModel::Validator

  # checks if a string is a number
  def is_numeric(o)
    true if Integer(o) rescue false
  end
  
  def validate(record)
    teams_to_create = record.user_input.split("\n")

    teams_to_create.each do |t|
      fields = t.split(" ")
      if fields.size < 3
        record.errors.add :user_input, "Missing Arguments"
      elsif fields.size > 3
        record.errors.add :user_input, "Too Many Arguments"
      else
        name = fields[0]
        date = fields[1]
        day = date.split("/")[0]
        month = date.split("/")[1]
        begin
          formatted_date = Date.parse("2022-" + month + "-" + day)
        rescue ArgumentError
          nil
        end
        group = fields[2]

        if !is_numeric(group)
          record.errors.add :user_input, "Group field must be an integer"
        end

        if formatted_date == nil
          record.errors.add :user_input, "Date field is an invalid format"
        end

        if Team.find_by(name: name) != nil
          record.errors.add :user_input, "Team is already registered"
        end
      end

      
    end

  end
end

class TeamsCreator < ApplicationRecord
  include ActiveModel::Validations
  validates :user_input, presence: true 
  validates_with TeamCreatorValidator
end

app/controllers/teams_creators_controller.rb
class TeamsCreatorsController < ApplicationController
  before_action :set_teams_creator, only: %i[ show edit update destroy ]

  # GET /teams_creators/new
  def new
    @teams_creator = TeamsCreator.new
  end

  # GET /teams_creators/1/edit
  def edit
  end

  # POST /teams_creators or /teams_creators.json
  def create
    @teams_creator = TeamsCreator.new(teams_creator_params)
    respond_to do |format|
      if @teams_creator.save
        # Create the respective registrations based on user input
        @user_inputs = @teams_creator.user_input.split("\n")
        @user_inputs.each do |input|
          fields = input.split(" ")
          name = fields[0]
          date = fields[1]
          day = date.split("/")[0]
          month = date.split("/")[1]
          begin
            formatted_date = Date.parse("2022-" + month + "-" + day)
          rescue ArgumentError
            nil
          end

          group = fields[2]

          Team.create(name: name, registration_date: formatted_date, group: group)
        end
        format.html { redirect_to teams_path, notice: "Teams are successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @teams_creator.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teams_creator
      @teams_creator = TeamsCreator.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def teams_creator_params
      params.require(:teams_creator).permit(:user_input)
    end
end

app/helpers/teams_creators_helper.rb
module TeamsCreatorsHelper
end

app/views/teams_creators/_form.html.erb
<%= form_with(model: teams_creator) do |form| %>
  <% if teams_creator.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(teams_creator.errors.count, "error") %> prohibited this teams_creator from being saved:</h2>

      <ul>
        <%@teams_creator.errors.messages.values.each do |msg| %>
          <%msg.each do  |m| %>
            <li><%= m %></li>
          <%end %>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_input, style: "display: block" %>
    <%= form.text_area :user_input %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/teams_creators/_teams_creator.html.erb
<div id="<%= dom_id teams_creator %>">
  <p>
    <strong>User input:</strong>
    <%= teams_creator.user_input %>
  </p>

</div>

app/views/teams_creators/edit.html.erb
<h1>Editing teams creator</h1>

<%= render "form", teams_creator: @teams_creator %>

<br>

<div>
  <%= link_to "Show this teams creator", @teams_creator %> |
  <%= link_to "Back to teams creators", teams_creators_path %>
</div>

app/views/teams_creators/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Teams creators</h1>

<div id="teams_creators">
  <% @teams_creators.each do |teams_creator| %>
    <%= render teams_creator %>
    <p>
      <%= link_to "Show this teams creator", teams_creator %>
    </p>
  <% end %>
</div>

<%= link_to "New teams creator", new_teams_creator_path %>
<%= link_to "Home", root_path %>

app/views/teams_creators/new.html.erb
<h1>New teams creator</h1>

<%= render "form", teams_creator: @teams_creator %>

<br>

<div>
  <%= link_to "Home", root_path %>
</div>

app/views/teams_creators/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @teams_creator %>

<div>
  <%= link_to "Edit this teams creator", edit_teams_creator_path(@teams_creator) %> |
  <%= link_to "Back to teams creators", teams_creators_path %>

  <%= button_to "Destroy this teams creator", @teams_creator, method: :delete %>
</div>